### ISSUE TITLE
Cannot find module './old/module'

### ISSUE THREAD

**Issue by campa** [data-uri/datauri#13]
Hi guys,

I'm trying to use _datauri_, but I'm not able to import it.
Inserting
`var datauri = require('datauri');`

 in my files, the import produces the error 

`Cannot find module './old/module'`

Mu context:
- Node version: v5.10.1
- Ubuntu Linux
-  "datauri": "^1.0.4", via npm
- npm version: 3.8.3

Any suggestions ? 
Thanks in advance

**Comment by heldr** [comment]
Hi @campa , just tried on Ubuntu 16 with node 5 and it worked for me.

Could you please **ls** your **node_modules/datauri** folder?

**Comment by amilajack** [comment]
```bash
➜  glsl-fast-gaussian-blur git:(master) ✗ ls node_modules/datauri 
api.js       module.js    package.json template
index.js     old          readme.md
➜  glsl-fast-gaussian-blur git:(master) ✗ 
```

**Comment by heldr** [comment]
Weird! BTW this folder will no longer exist on version 2.0 though.

It might be released next week
https://github.com/heldr/datauri/tree/new

**Comment by heldr** [comment]
Fixed https://github.com/data-uri/datauri/releases/tag/v2.0.0
