### ISSUE TITLE
Encode from stream

### ISSUE THREAD

**Issue by FallingSnow** [data-uri/datauri#17]
Is it possible to encode data coming from a string or is it necessary to pipe it into buffer first?

**Comment by heldr** [comment]
Sorry for the delay. Yes! Using `format` method. Might be a simple `require('datauri/format')` on version 2.0.

For now:

```js
const Datauri = require('datauri');
const datauri = new Datauri();

console.log(datauri.format('.txt', 'hello world').content);
```
