### ISSUE TITLE
If we pass a data URI to `new DataURI` - should we simply return it?

### ISSUE THREAD

**Issue by niftylettuce** [data-uri/datauri#21]
I ran into an edge case with <https://github.com/jrit/web-resource-inliner> - specifically here <https://github.com/jrit/web-resource-inliner/blob/6ca0b528b6e7020c9782bc7d8ccbc5ea83818ae0/src/util.js#L184> where the `src` passed was actually a data URI component in itself.  I will be submitting a PR to `web-resource-inliner` that sniffs if it's a data URI or not in that block of code, and if so, return the callback early - however I think that perhaps it should be built into this package?

My logic was, if we have a function... for example... named convertPathToString, it should return a string as the output.  If we pass a string initially, it should just return the same thing.

Could use `validator`'s `isDataURI` function here <https://github.com/chriso/validator.js/blob/3443132beccddf06c3f0a5e88c1dd2ee6513b612/src/lib/isDataURI.js> or import `validator` and use `validator.isDataURI`.

**Comment by tommedema** [comment]
Seems like a good proposal. I would indeed import validator if it were my decision to make.

**Comment by heldr** [comment]
FIxed
