### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by moffsugita** [data-uri/datauri#24]
```
> npm install @types/datauri
npm ERR! code E404
npm ERR! 404 Not Found: @types/datauri@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-12-07T09_18_49_613Z-debug.log
```

it looks like good tool but typescript not supported?
I just want to convert image path to data uri `create react apps` project...

**Comment by heldr** [comment]
it's coming! I'll generate type definitions in module itself :)

**Comment by ramtinsoltani** [comment]
@heldr Any updates on this?

**Comment by abcfy2** [comment]
Any updates on this?

**Comment by heldr** [comment]
Being very transparent, I got too busy with work recently(since I lead a team), PRs are very welcome too. Going to do my best to get something this month. Sorry!

**Comment by vecerek** [comment]
Any updates? 🙂

**Comment by baiguinimattia** [comment]
Any updates?

**Comment by talhabalaj** [comment]
Any updates?

**Comment by heldr** [comment]
Done!

**Comment by heldr** [comment]
More info in https://github.com/data-uri/datauri/releases/tag/v3.0.0
