### ISSUE TITLE
M4A Audio is not handled

### ISSUE THREAD

**Issue by thoni56** [data-uri/datauri#26]
Apple format audio is converted to octetstream. A file with this signature (using `file`):

    ... ISO Media, Apple iTunes ALAC/AAC-LC (.M4A) Audio

will result in

    data:application/octet-stream;base64,AAAAIGZ0e...

This cannot be played by the HTMLAudioElement.

**Comment by heldr** [comment]
Sorry for the delay.

Apparently this extension is not part of IANA Media types as per https://www.iana.org/assignments/media-types/media-types.xhtml#audio

**Comment by heldr** [comment]
Sorry for the delay.

Apparently this extension is not part of IANA Media types as per https://www.iana.org/assignments/media-types/media-types.xhtml#audio , which is followed by datauri submodule https://github.com/data-uri/mimer

Other than that, I believe is a good idea to allow custom mimetypes in datauri as per mimer submodule.

**Comment by heldr** [comment]
My bad! m4a is actually there https://www.iana.org/assignments/media-types/media-types.txt

**Comment by heldr** [comment]
mimer parses apache mime types file(based on IANA's spec), the good news is that `m4a` will be supported on next datauri release 😄 

As per [mime.types](https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types) from Apache:
```
audio/mp4					m4a mp4a
```

**Comment by heldr** [comment]
Fixed in https://github.com/data-uri/datauri/releases/tag/v2.0.0
